language: generic

matrix:
  fast_finish: true

# Run in ubuntu-trusty environment
dist: trusty
sudo: required

# OS packages
addons:
  apt:
    packages: [uidmap, vagga]
    sources:
      - sourceline: >-
          deb [arch=amd64 trusted=yes] http://ubuntu.zerogw.com vagga-testing main

# Cache .vagga images to speedup sequential builds
cache:
  timeout: 21600 # 6 hours
  directories:
   - .vagga/.roots
   - .vagga/.mnt
   - .vagga/.transient

# Scripts to install dependencies
# These are mostly honestly borrowed from https://github.com/tailhook/vagga/tree/master/.travis.yml
before_install:
  - 'echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml'
  - echo "$(id -un):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid

install: vagga _build nodejs-7-ubuntu-bin

# Run tests
script: vagga test

# Docker analog
sudo: required

language: javascript

services:
  - docker

before_install:
  - docker build -t events-parser:latest .
  - docker run  --rm events-parser:latest
  - docker ps -a

script: 
  - standard